stages:
  - build
  - start
  - stop
  - prod


build:
  stage: build
  script:
    - docker build -t stats_bot:master-1 .
  tags:
    - bot
  only:
    - merge_requests


deploy:
  stage: start
  script:
    - docker run -it stats_bot:master-1
  tags:
    - bot
  only:
    - merge_requests

stop:
  stage: stop
  script:
    - docker stop stats_bot:master-1
  tags:
    - bot
  when: manual
  only:
    - merge_requests

prod:
  stage: prod
  script:
    - docker build -t stats_bot:prod .
    - docker start -it stats_bot:prod -d
  when: manual