stages:
  - deploy
  - test


deploy:
  stage: deploy
  before_script:
    - sudo systemctl stop tg_bot.service
  script:
    - sudo rsync -a --info=progress2 --delete . $SERVER_DIR/
    - rm -rf $SERVER_DIR/venv
    - python3.8 -m venv $SERVER_DIR/venv && source $SERVER_DIR/venv/bin/activate && pip install -r $SERVER_DIR/requirments.txt
  after_script:
    - sudo systemctl start tg_bot.service
  tags:
    - ya-runner

test:
  stage: test
  script:
    - systemctl is-active --quiet tg_bot.service
  tags:
    - ya-runner